### ISSUE TITLE
Resetting some keybindings

### ISSUE THREAD

**Issue by mikaela01a** [Charismara/Beloved-Keybindings#1]
Mod version 0.0.9.0 for Minecraft 1.16.5
Every time I log into the same version of minecraft, which is forge 36.1.0, it resets only a couple of my key bindings if they were saved. Specifically the ones related to HWYLA, Quark, and the sprint hotkey.
I have tried trashing them, rebinding them, and then resaving them and that did not work. it only kept the keybindings if they weren't saved.

**Comment by Charismara** [comment]
Hmm that's weird. 

Could you save the problematic keybindings, close the game, restart again and send me the debug log (using pastebin) of that session?

Your Minecraft uuid and the key you want to use would be helpful too.

I'll take a look on that as soon as possible!:)

**Comment by mikaela01a** [comment]
Hi sorry, im not sure what was happening to make this glitch but it is no longer happening. I reloaded my game a couple of times just now with loading into a world and without and it kept the key bindings for me after i saved them. 
While the glitch was happening i reloaded it several times to try and fix it before i submitted this. 
Ill try and check every so often just in case it randomly happens again.

**Comment by Charismara** [comment]
No problem 😊 the main thing is that it works. 
I'll close this issue and if you encounter the bug again, feel free to reopen the issue!

Thanks for reporting 👍
